config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "augurys#index"
  resources :augurys, only: [:index, :new, :create, :show] do
    resources :results, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/augury.rb
class Augury < ApplicationRecord
  belongs_to :user
  has_one :result

  validates :nickname, presence: true
  validates :sign, presence: true
  validates :birth_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :augury
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :augury
  has_one :result

  validates :name, presence: true
  validates :birth_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birth_id ])
  end
end

app/controllers/augurys_controller.rb
class AugurysController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def index
    @augurys = Augury.all
  end

  def new
    @augury = Augury.new
  end

  def create
    @augury = Augury.new(augury_params)
    if @augury.save
      redirect_to augury_path(@augury)
    else
      render :new
    end
  end

  def show
    @augury = Augury.find(params[:id])
  end

    private

  def augury_params
    params.require(:augury).permit(:nickname, :sign, :birth_id).merge(user_id: current_user.id)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @result = Result.all
    @result = Augury.find(params[:augury_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/augurys_helper.rb
module AugurysHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/augurys/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/augurys/index.html.erb
<div class="contents">
  <div class="first-view">
    <img src="images/sample1.jpeg" alt="トップ画像" class="top-image">
    <h2 class="service-title">
      今日の運勢占いませんか？
    </h2>
    <p class="service-explain">
      新規入会するだけで無料で占う事ができます
    </p>
    <h2 class="logo">
      今日の運勢を占う
    </h2>
    <%= link_to "占う", new_augury_path, class: "send-bot" %>
  </div>
  <div class="upper-content">
    <h2 class="heading-name">新着情報</h2>
    <ul class="messages">
      <li class="message">
        <div class="message-date">2022/10/06</div>
        <div>【新規のお客さま限定】<b>10%OFF</b>キャンペーン</div>
      </li>
      <li class="message">
        <div class="message-date">2022/10/03</div>
        <div>うれしい<b>ポイントアップキャンペーン</b></div>
      </li>
      <li class="message">
        <div class="message-date">2022/09/27</div>
        <div>【会員限定】<b>20%OFF</b>キャンペーン</div>
      </li>
      <li class="message">
        <div class="message-date">2022/10/03</div>
        <div>うれしい<b>ポイントアップキャンペーン</b></div>
      </li>
      <li class="message">
        <div class="message-date">2022/09/27</div>
        <div>会員4万人登録達成</div>
      </li>
    </ul>
  </div>
  <div class="middle-content">
    <h2 class="heading-name">占い師リスト</h2>
    <ul class="stylist-list">
      <li>
        <img src="images/sample2.jpeg" alt="staff1" class="stylist-image">
        <h4 class="stylist-name">インチキ親父</h4>
      </li>
      <li>
        <img src="images/sample4.jpeg" alt="staff2" class="stylist-image">
        <h4 class="stylist-name">チェリーブロッサム</h4>
      </li>
      <li>
        <img src="images/sample3.jpeg" alt="staff3" class="stylist-image">
        <h4 class="stylist-name">タロット 米沢</h4>
      </li>
    </ul>
  </div>
  <div class="bottom-content">
    <form class="contact-form">
        <h2 class="heading-name">お問い合わせ</h2>
        <input type="text" placeholder="name" class="small-field">
        <input type="text" placeholder="e-mail" class="small-field">
        <textarea placeholder="message" class="large-field"></textarea>
        <input type="submit" value="SEND" class="send">
      </form>
  </div>
</div>

app/views/augurys/new.html.erb
<%= form_with model: @augury, url: augurys_path, local: true do |f| %>
<%= render "error_messages", model: f.object %>
<div class="form-wp">
  <div class="form-header">
    <h3 class="form-header-text">
      投稿する 
    </h3>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">nickname</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :nickname, class:"input-default", id:"nickname", placeholder:"例) 山本太郎", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">星座</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :sign, class:"input-default", id:"sign", placeholder:"例) 蟹座", maxlength:"10" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_id,
                    class:'select-birth',
                    id:"birth_id",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
      <%= f.submit "占ってみる", class:"register-btn" %>
    <% end %>
</div>

app/views/augurys/show.html.erb
<div class="form-wp">
  <div class="form-header">
    <h3 class="form-header-text">
      完了しました
    </h3>
  </div>

  <%= link_to "占い結果を見てみる", augury_results_path(@augury), class: "send-second-bot" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DivinationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <header>
      <div class="heading">
        <h1 class="title"><a href="/">Divination App</a></h1>
      </div>
      <div class="navbar">
        <% if user_signed_in? %>
          <div class="nav-list">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-new" %>
          </div>
        <% else %>
          <div class="nav-list">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-new" %>
            <%= link_to "ログイン", new_user_session_path, class: "nav-login" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <footer class="footer">
        <p class="copyright">Copyright © DIVINATION APP All rights reserved.</p>
      </footer>
    </footer>
  </body>
</html>

app/views/results/index.html.erb
<%= form_with model: @result, local: true do |f| %>
<div class="form-wp">
  <div class="form-header">
    <%= "#{@result.nickname}さんの運勢は..." %>
  </div>
  <% case @result.sign when "牡羊座","牡牛座","双子座" %>
    <div class="main-tc">
      <div class="main-second">
        <h2>
        <p class="text-message">大吉です！！</p>
        素晴らしい一日になるでしょう。
        </h2>
      </div>
    </div>
  <% when "蟹座","獅子座","乙女座" %>
    <div class="main-tc">
      <div class="main-second">
        <h2>
        <p class="text-message">吉です！！</p>
        今日はカレーを食べるといい事あるでしょう。
        </h2>
      </div>
    </div>
  <% when "天秤座","魚座","射手座" %>
    <div class="main-tc">
      <div class="main-second">
        <h2>
        <p class="text-message">凶です！！</p>
        謙虚な気持ちで過ごしましょう。
        </h2>
      </div>
    </div>
  <% else %>
    <div class="main-tc">
      <div class="main-second">
        <h2>
        <p class="text-message">大凶です！！</p>
        自分を客観的に見つめ直す必要がありそうです。
        </h2>
      </div>
    </div>
  <% end %>
  <%= link_to "トップページ", root_path, class:"bottom-btn" %>
<% end %>
</div>